### ISSUE TITLE
Hacker's Gate のロゴ

### ISSUE THREAD

**Issue by cocoeyes02** [hacker-s-gate/org#2]
Hacker's Gate のロゴ欲しい…欲しくない？

## 何故やりたいか
* Hacker’s Gate のブランディング
* connpass、[Twitter](https://twitter.com/hackersgate) や [ノベルティ](https://github.com/hacker-s-gate/org/issues/5)で使用したい

## 目指すべきゴールは何か
* ロゴの作成

## ロゴである利点
* 今後の Hacker’s Gate の活動で、バンバン使っていくことができる
* イベント終了後も、Hacker’s Gate や WG のことを覚えている人が増える
	
## 決まっていないこと・わかっていないこと例
* 費用はいくらかかるのか、どこから出すのか
* ロゴのコンセプト
* 誰がデザインするのか

**Comment by cocoeyes02** [comment]
デザインをお願いするにしても、ロゴのコンセプトは必要なので考えたいですね！

ちなみに過去に話した案だと
H（Hacker's Gate） + ゲート で以下のロゴ案がありましたね

<img width="449" alt="スクリーンショット 2019-02-13 17 05 51" src="https://user-images.githubusercontent.com/21007314/55369109-2049a800-5530-11e9-836b-4667684286e3.png">

**Comment by cureseven** [comment]
京都工芸繊維大学の友達がデザインの勉強しているので，よければ依頼して良いですか．
無料でやってくれると思うしお金出したら喜ぶと思います．

**Comment by okashoi** [comment]
無償というのはいただけないので、もしやってもらえるなら何らかの見返りがあるようにはしたい（いまのところ個人意見）

**Comment by mism-mism** [comment]
個人的には、無償は絶対良くないと思ってる
製作者の仕事に対する対価は渡すべきだし
製作者以外のデザイナーの人はなにかを作って対価をもらってるはずだし

**Comment by cureseven** [comment]
わかりました，では
> 費用はいくらかかるのか、どこから出すのか

ですね．誰に権限がありますか？

**Comment by klack710** [comment]
もしそれでも困ったら、私もデザイナーの卵(同人界隈では既に仕事してる)の知り合いいるから、
私にも相談していただけたらよきー

**Comment by okashoi** [comment]
> 誰に権限がありますか？

広報管轄になりそうなので、私の方で予算取れるか確認します～

**Comment by okashoi** [comment]
予算の話、詳しいところに踏み込むとオープンにできないかもなので、そうなったら 社の slack にて

**Comment by cocoeyes02** [comment]
> 費用はいくらかかるのか、どこから出すのか
> 誰がデザインするのか

この辺りはいい感じに解決しそうで良いですね！:azamasu:

あとはここかな〜〜〜
> ロゴのコンセプト

**Comment by okashoi** [comment]
@各位

予算周りの話はいったん社の slack に書きました。質問等あればそちらで。

**Comment by 8845musign** [comment]
ロゴ、ですが

基本的にはブランディングのためにやるものです。  
ブランディングは「他とどう違うのか」を明確に定義してあらゆるシーンで差異化を図るものです。

「なぜやるか」を十分に深掘りせずにできたロゴは逆に足枷になることもあります。

クオリティだけでいったら、勉強会ではキレイなロゴは巷にたくさんあふれていますが、
効果出ているのかと言うとどうでしょう。

無償で頼むなら、設計にはなかなか期待できませんし、  
有償にしてもそれ相応のお金を積むか、  
発注者の我々がちゃんと発注するための意図を取りまとめをする必要があります。

なので活動や方針がしっかり固まるまでは必要ないんじゃないかな

すでに会社のブランディングが、しっかりしたものがあるのでそれを継承する形でもまずはいいんじゃないかなと思います。

**Comment by cocoeyes02** [comment]
なるほど！

確かに主目的は Hacker’s Gate のブランディングだよなあ、っていうのは僕も思っていました！

> なので活動や方針がしっかり固まるまでは必要ないんじゃないかな

確かに活動や方針も試行錯誤中ですし、お金もかかるのであれば軽い気持ちで作れませんからね

「活動や方針、体制を整えた上でどういうブランディングをしていきたいのか」が先決になりそう

**Comment by miyanishi-yuki** [comment]
Hacker's GATE自体、今はいいなと思ったことをなんでもやろう！のフェーズなので、
Hacker's GATEに対してロゴを作るというより、もっと小さな単位の方が意味はあるのかなと思いました。
「いろんなことやっているウィルゲートの勉強会」のロゴより、
例えば「もくもく会のロゴ」とかの方が、配布する時にも意味がありそう。。
